# Generated by Django 3.0.4 on 2020-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('img', models.FileField(upload_to='')),
                ('title', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
            ],
        ),
    ]
